services:
  backend:
    image: prasadbhoite16/django-backend:latest
    container_name: django-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false

  frontend:
    image: prasadbhoite16/react-frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
